### ISSUE TITLE
You have a broken link 

### ISSUE THREAD

**Issue by pstaszko** [puppetmaster-/vampire_survivors_mods#2]
I get a 404 on this link
https://github.com/puppetmaster-/vampire_survivors/blob/main/map_garden/_install.md
It looks like it should be
https://github.com/puppetmaster-/vampire_survivors/blob/main/map_garden/install.md

**Comment by puppetmaster-** [comment]
Thanks for reporting
fix in [link corrected](https://github.com/puppetmaster-/vampire_survivors_mods/commit/a300a5cdd98d9975f567c2d41ad495d930194f92)
