### ISSUE TITLE
Typo in the stageName

### ISSUE THREAD

**Issue by Kadagaden** [puppetmaster-/vampire_survivors_mods#4]
There's a typo:

'stageName': 'Secre**d** Garden'

The description (README) says 'Secre**t'**

**Comment by puppetmaster-** [comment]
thanks for reporting
fix in [fix typo](https://github.com/puppetmaster-/vampire_survivors_mods/commit/d5bf2fac2f17238a9a1dac0192170a2bd0827bb2)
